name: C++ CI with Valgrind and Clang-Tidy

on: [push]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out repository code

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.apt-cache
            ~/cmake-cache
            key: ${{ runner.os }}-deps-cmake-${{ hashFiles('**/apt-get-install.txt', '**/CMakeLists.txt') }}
            restore-keys: |
              ${{ runner.os }}-deps-cmake-
  
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake valgrind clang-tidy
          xargs apt-mark auto < apt-get-install.txt > /dev/null

      - name: Configure CMake
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/cmake-cache
          cmake -B ~/cmake-cache -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: cmake --build ~cmake-cache --parallel